name: Ion Channel Data Viewer
description: A web-based viewer for ion channel data and PDB structures
url: https://Harryw6.github.io/ionchannel_publish
baseurl: /ion_channel

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - script.js
  - styles.css

# Include files
include:
  - _config.yml
  - index.html
  - mpnn_results.csv
  - script.js
  - start_server.bat
  - styles.css
  - all_pdb/*

# GitHub Pages settings
github:
  repository_name: ionchannel_publish
  repository_url: https://github.com/Harryw6/ionchannel_publish

# SEO settings
title: Ion Channel Data Viewer
author: WXH
lang: zh-CN
locale: zh_CN
